## Donating Virtual Machine to Armbian?

Our CI engine is hungry for CPU and memory resources. In case you have spare resources and you would like to donate it to Armbian, you can do it this way:

We divide runners by arhitecture (ARM64 or X86) and size (big/small).

1. Memory = 6Gb for "small", 16Gb for "big"
3. Core count = 4 for "small", 12 + for "big"
4. Space = 64Gb

https://www.armbian.com/contact/
<!--START_SECTION:data-section-->
<!--END_SECTION:data-section-->
