name: Update beta repo on cron
on:
  schedule:
    - cron:  '0 * * * *' 
jobs:
  build: 
    runs-on: [runner2]
    steps:
      - name: Run script
        shell: bash {0}
        run: |
          run-one ./beta-repository.sh
