name: Check & build kernels
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  build: 
    runs-on: [runner2]
    steps:
      - name: Run script
        shell: bash {0}
        run: |
          bash beta-repository.sh
