name: Check & build kernels
on:
  schedule:
    - cron:  '*/5 * * * *' 
jobs:
  build: 
    runs-on: [runner2]
    steps:
      - name: Run script
        shell: bash {0}
        run: |
          run-one bash beta-repository.sh
