name: "Sync maintainers status"

# Script connects to the contacts database every 8 hours and updates
# BOARD_MAINTAINER property in the board config files. If there are any changes,
# it opens a Pull Request to https://github.com/armbian/build
#
# spdx-id: GPL-2.0-or-later
# copyright-owner: Igor Pecovnik

# Dependencies: lftp, jq

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:

  Build:
    name: Maintainers sync
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'armbian' }}
    steps:

      - name: Checkout build repo
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref:  main
          fetch-depth: 0
          clean: false

      - name: Install SSH key for storage
        env:
          KEY_ARMBIAN_UPLOAD: ${{ secrets.KEY_ARMBIAN_UPLOAD }}
        if: env.KEY_ARMBIAN_UPLOAD != null
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY_ARMBIAN_UPLOAD }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_ARMBIAN_UPLOAD }}
          if_key_exists: replace

      - name: Get JSON file
        env:
          KEY_TORRENTS: ${{ secrets.KEY_TORRENTS }}
        if: env.KEY_TORRENTS != null
        run: |

          # install dependencies
          sudo apt-get -y -qq install lftp jq

          # download json that is prepared for this action in another cron job
          lftp -u upload, -e "cd json; get -O /tmp/ armbian_maintainers.json ;bye" sftp://${{ secrets.ARMBIAN_HOST_UPLOAD }}

          # reset all maintainers so we generate from scratch
          sed -i "s/BOARD_MAINTAINER.*/BOARD_MAINTAINER=\"\"/" config/boards/*.{conf,wip,eos,tvb}

          # extract values fron JSON
          {
            jq -c '.[]' /tmp/armbian_maintainers.json | while read i; do
              NAME=$(echo $i | jq --raw-output '.First_Name')
              BOARD=$(echo $i | jq --raw-output '.Maintaining')
              MAINTAINER_GITHUB=$(echo $i | jq --raw-output '.Github' | cut -d"/" -f4)
              if [[ $BOARD != null && $MAINTAINER_GITHUB != null ]]; then
                echo "- [$NAME](https://github.com/${MAINTAINER_GITHUB})"
                for i in $(echo $BOARD | sed "s/,/ /g"); do
                  unset BOARD_NAME BOARD_MAINTAINER CFG_CONTENT
                  CFG_CONTENT="$(cat config/boards/${i}.* 2> /dev/null | grep -e "BOARD_MAINTAINER\|BOARD_NAME" || true)"
                  if [[ -n "$CFG_CONTENT" ]]; then
                    eval "$CFG_CONTENT"
                    echo -e "  - $i</li>"
                    if [[ -n "${BOARD_MAINTAINER}" && "${BOARD_MAINTAINER}" != *$MAINTAINER_GITHUB* ]]; then
                      BOARD_MAINTAINER+=" $MAINTAINER_GITHUB"
                    else
                      BOARD_MAINTAINER="$MAINTAINER_GITHUB"
                    fi
                    sed -i "s/BOARD_MAINTAINER.*/BOARD_MAINTAINER=\"$BOARD_MAINTAINER\"/" config/boards/${i}.*

                    # if maintainer exits, rename .csc to .conf
                    if [[ -n "${BOARD_MAINTAINER}" ]]; then
                      mv config/boards/${i}.csc config/boards/${i}.conf 2>/dev/null || true
                    fi
                  fi
                done
              fi
            done

            # rename configuration to .csc where we lost maintainer
            grep BOARD_MAINTAINER=\"\" config/boards/*.{wip,conf} | cut -d":" -f1 |
              while read -r line; do
                if [[ "${line}" != "${line/.conf/.csc}" ]]; then
                  mv $line ${line/.conf/.csc}
                fi
                if [[ "${line}" != "${line/.wip/.csc}" ]]; then
                  mv $line ${line/.wip/.csc}
                fi
              done

          } >> $GITHUB_STEP_SUMMARY

          # Re-generate CODEOWNERS
          ./.github/generate_CODEOWNERS.sh 

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-maintainers
          delete-branch: true
          title: '`Automatic` board configs status synchronise'
          body: |            
            Update maintainers and board status

            - synced status from the database
            - rename to .`csc` where we don't have anyone

            If you want to become a board maintainer, [adjust data here](https://www.armbian.com/update-data/).

            Ref: [Board Maintainers Procedures and Guidelines](https://docs.armbian.com/Board_Maintainers_Procedures_and_Guidelines/)
            
          labels: |
            Maintenance :recycle:
          #assignees: igorpecovnik
          #reviewers: Must be org collaborator
          draft: false
