name: Update beta repo on push
on:
  push:
    branches:
      - master
jobs:
  build: 
    runs-on: [runner2]
    steps:
      - name: Run script
        shell: bash {0}
        run: |
          run-one ./beta-repository.sh
