name: Test inside container

on:

  workflow_dispatch:
  workflow_call:
    inputs:
      url:
        required: false
        type: string
      package:
        required: false
        type: string


jobs:  

  gradle:
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        image: ["debian:buster","debian:bullseye","debian:sid","ubuntu:focal","ubuntu:jammy","ubuntu:kinetic"]
    
    name: Install into
    runs-on: ubuntu-latest
    container:
        image: "${{ matrix.image }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Show
        run: |


          echo ${{ inputs.url }}
          echo ${{ inputs.package }}
          RELEASE=$(echo "${{ matrix.image }}" | cut -d":" -f2)
          apt update
          apt -y install wget gpg
          wget https://apt.armbian.com/armbian.key -O key
          gpg --dearmor < key | tee /usr/share/keyrings/armbian.gpg > /dev/null
          chmod go+r /usr/share/keyrings/armbian.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/armbian.gpg] http://apt.armbian.com $RELEASE main ${RELEASE}-utils ${RELEASE}-desktop" | tee /etc/apt/sources.list.d/armbian.list
          apt update
